# Generated by Django 5.1.1 on 2024-11-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_view_all_recipients", "can view all recipients"),
                    ("can_manage_users", "can manage users"),
                    ("can_view_all_mailings", "can view all mailings"),
                    ("can_block_users", "can block users"),
                    ("can_disable_mailings", "can disable mailings"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
