# Generated by Django 5.1.1 on 2024-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="укажите время в формате 2023-10-01 12:00",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_time",
            field=models.DateTimeField(
                blank=True,
                help_text="укажите время в формате 2023-10-01 12:00",
                null=True,
            ),
        ),
    ]
