# Generated by Django 5.1.1 on 2024-10-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0002_alter_mailing_end_time_alter_mailing_first_send_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={},
        ),
    ]
