# Generated by Django 5.1.1 on 2024-10-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="attempt_time",
            new_name="attempt_datetime",
        ),
    ]
