# Generated by Django 5.1.1 on 2024-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0006_usermailingstatistics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["owner"],
                "permissions": [("can_block_mailing", "can block mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_block_email", "can block email")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
