# Generated by Django 5.1.1 on 2024-11-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0007_alter_mailing_options_alter_recipient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
