# Generated by Django 5.1.1 on 2024-11-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0011_alter_message_options_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "can view all mailings"),
                    ("can_disable_mailings", "can disable mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
