# Generated by Django 5.1.1 on 2024-11-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0012_alter_mailing_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "permissions": [("can_view_all_mailings_attempts", "can view all mailings attempts")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытка рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_all_messages", "can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
